http {
  body_size 1024; # Request body size limit

  server {
    listen 127.0.0.1:8080; # interface:port pairs 
    name first.com; # server id
    
    error_page 404 /404.html; # Error pages
    error_page 500 502 503 504 /50x.html;

    location / {
      accept GET POST; # Accepted methods by endpoint
      root /data/www; # File resolution directory
      index index.html index.htm; # default file to server
      autoindex off; # on / off, directory listing
    }

    location /test {
      accept GET;
      root /tmp/www; # /test/page should map to /tmp/www/page
    }

    location /redirection {
      redirect 301 http://example.com/new-url; # HTTP redirection
    }

    location /upload {
      accept POST GET;
      root /data/www/uploads;

      upload on; # authorization
      upload_store /data/www/uploads/files; # upload location
    }

    location /cgi-bin {
      accept GET POST;
      root /data/www/cgi-bin;
      cgi_pass .php /usr/bin/php-cgi; # Execution of CGI based on file extension
      cgi_pass .py /usr/bin/python3; # cgi_pass <extension> <executable_path>
    }
  }
  server {
    listen 127.0.0.1:8081;
    name second.com;

    location / {
      root /var/www/html;
      accept GET;
      autoindex on;
    }
  }
}